from datetime import datetime
from cs50 import SQL
db = SQL('sqlite:///dados.db')
dia = datetime.now().date()

data = db.execute("SELECT id,item,preco,opcoes FROM cardapio WHERE id<=45")
dados_atualizados = [{'id': 1, 'preco': 38, 'opcoes': 'Tamanho(300g-500g+18-1kg+65)Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 2, 'preco': 50,
                         'opcoes': 'Tamanho(300g-500g+24-1kg+88)Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 3, 'preco': 56,
                         'opcoes': 'Tamanho(300g-500g+29-1kg+106)Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 4, 'preco': 62,
                         'opcoes': 'Tamanho(300g-500g+35-1kg+123)Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 5, 'preco': 62,
                         'opcoes': 'Tamanho(300g-500g+35-1kg+123)Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 6, 'preco': 67,
                         'opcoes': 'Tamanho(300g-500g+45-1kg+133)Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 7, 'preco': 74,
                         'opcoes': 'Tamanho(300g-500g+41-1kg+147)Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 8, 'preco': 75,
                         'opcoes': 'Tamanho(300g-500g+42-1kg+150)Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 9, 'preco': 144,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 10, 'preco': 144,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 11, 'preco': 156,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 12, 'preco': 160,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 13, 'preco': 162,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 14, 'preco': 165,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 15, 'preco': 170,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 16, 'preco': 174,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 17, 'preco': 179,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 18, 'preco': 185,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 19, 'preco': 115,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 20, 'preco': 127,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 21, 'preco': 138,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 22, 'preco': 144,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 23, 'preco': 156,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 24, 'preco': 156,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 25, 'preco': 156,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 26, 'preco': 160,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 27, 'preco': 174,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 28, 'preco': 197,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 29, 'preco': 200,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 30, 'preco': 205,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 31, 'preco': 215,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 32, 'preco': 220,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 33, 'preco': 220,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 34, 'preco': 226,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 35, 'preco': 244,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 36, 'preco': 236,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 37, 'preco': 236,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 38, 'preco': 244,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 39, 'preco': 245,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 40, 'preco': 256,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 41, 'preco': 260,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 42, 'preco': 268,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 43, 'preco': 290,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 44, 'preco': 291,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     {'id': 45, 'preco': 309,
                         'opcoes': 'Adicionais(cheddarEbacon+20-cebola empanada+17)'},
                     ]
for i in range(45):
    preco = dados_atualizados[i]['preco']
    opcoes = dados_atualizados[i]['opcoes']
    id = i+1
    db.execute("UPDATE cardapio SET preco = ?, opcoes = ? WHERE id = ?",preco,opcoes,id)

print(db.execute('SELECT id,item,preco,opcoes FROM cardapio WHERE id <= 45'))